defaults:
  - data: audioset
  - optimizer: adamW
  - trainer: default_trainer
  - patching: frame
  - ssl: jepa 
  - routea: ce_target

model: GRAM-T
model_size: base
save_dir: /projects/0/prjs1338
seed: 42
